export const SET_SEARCH = "SET_SEARCH";
export const SET_GENRES = "SET_GENRES";
export const SET_LOADED = "SET_LOADED";
export const SET_PAGINATION = "SET_PAGINATION";
export const SET_GENRESFORSEARCH = "SET_GENRESFORSEARCH";
export const SET_FLAGFORGENRE = "SET_FLAGFORGENRE";